// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEe9pviD9_JlT6BWnfIFdQsN1BZCwGXPw',
    appId: '1:769755457924:android:90f5f4830c9d0d772cd5d1',
    messagingSenderId: '769755457924',
    projectId: 'vivattendance',
    storageBucket: 'vivattendance.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD01QGa5EIafzguSGDp4ia0gCXfMAS3xZM',
    appId: '1:769755457924:web:5241bdfe9737a9562cd5d1',
    messagingSenderId: '769755457924',
    projectId: 'vivattendance',
    authDomain: 'vivattendance.firebaseapp.com',
    storageBucket: 'vivattendance.appspot.com',
    measurementId: 'G-XPN69R3FHT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA381-l6Ddh9_w5E9M6ezVe2lrjJM0vWac',
    appId: '1:769755457924:ios:9edbea22ece73dbf2cd5d1',
    messagingSenderId: '769755457924',
    projectId: 'vivattendance',
    storageBucket: 'vivattendance.appspot.com',
    iosBundleId: 'com.example.flutterAbsensiApp',
  );

}